apiVersion: v1
kind: Pod
metadata:
    name: busybox
spec:
    containers:
        - image: busybox
          name: busybox
          command:
              - sleep
              - "3600"
          imagePullPolicy: IfNotPresent
    restartPolicy: Always
    dnsPolicy: "None"
    dnsConfig:
        nameservers:
            - 8.8.8.8
        searches:
            - example.com
